### ISSUE TITLE
Неверная ссылка в README.md

### ISSUE THREAD

**Issue by sayat-a** [Hexlet/ru-projects-for-contributing#11]
Summary: В файле README.MD в описаниях проектов "Игры разума" и "Hexlet CV" по ссылке "Подробнее"(/projects/ecodomen/README.md) открывается описание проекта Ecodomen

**Comment by fey** [comment]
@sayat-a пришлете ПР с исправлением?

**Comment by sayat-a** [comment]
Отправил ПР

**Comment by sayat-a** [comment]
Исправлено
