### ISSUE TITLE
Большие игроки на рынке российского опенсорса

### ISSUE THREAD

**Issue by AABur** [Hexlet/ru-projects-for-contributing#5]
Список больших игроков на рынке российского опенсорса. Стоит ли добавлять их в основной список не очевидно, но и терять не стоит. Пусть здесь полежат. Пополнение списка приветствуется.

https://github.com/sberbank-ai
https://github.com/hhru
https://github.com/Tinkoff
https://github.com/avito-tech
https://github.com/yandex
https://github.com/yandex-cloud

**Comment by fey** [comment]
Продублируешь сюда? https://github.com/Hexlet/ru-awesome-opensource

**Comment by fey** [comment]
Давай посмотрим, какие из этих проектов действительно полезные для сообщества :) А не решают задачу конкретной компании

**Comment by AABur** [comment]
Ок занесу в Hexlet/ru-awesome-opensource, и заодно поправлю там форматирование.
